# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _kipr
else:
    import _kipr

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


KIPR_GIT_BRANCH = _kipr.KIPR_GIT_BRANCH
KIPR_GIT_COMMIT_HASH = _kipr.KIPR_GIT_COMMIT_HASH
KIPR_VERSION_MAJOR = _kipr.KIPR_VERSION_MAJOR
KIPR_VERSION_MINOR = _kipr.KIPR_VERSION_MINOR
KIPR_VERSION_PATCH = _kipr.KIPR_VERSION_PATCH
KIPR_VERSION = _kipr.KIPR_VERSION
KIPR_BUILD_DATETIME = _kipr.KIPR_BUILD_DATETIME

def accel_x():
    return _kipr.accel_x()

def accel_y():
    return _kipr.accel_y()

def accel_z():
    return _kipr.accel_z()

def accel_calibrate():
    return _kipr.accel_calibrate()

def analog(port):
    return _kipr.analog(port)

def analog8(port):
    return _kipr.analog8(port)

def analog10(port):
    return _kipr.analog10(port)

def analog12(port):
    return _kipr.analog12(port)

def analog_et(port):
    return _kipr.analog_et(port)

def set_analog_pullup(port, pullup):
    return _kipr.set_analog_pullup(port, pullup)

def get_analog_pullup(port):
    return _kipr.get_analog_pullup(port)

def beep():
    return _kipr.beep()

def battery_charging():
    return _kipr.battery_charging()

def power_level():
    return _kipr.power_level()

def power_level_nimh():
    return _kipr.power_level_nimh()

def power_level_lipo():
    return _kipr.power_level_lipo()

def power_level_life():
    return _kipr.power_level_life()

def shut_down_in(s):
    return _kipr.shut_down_in(s)

def wait_for_light(light_port_):
    return _kipr.wait_for_light(light_port_)

def set_a_button_text(text):
    return _kipr.set_a_button_text(text)

def set_b_button_text(text):
    return _kipr.set_b_button_text(text)

def set_c_button_text(text):
    return _kipr.set_c_button_text(text)

def set_x_button_text(text):
    return _kipr.set_x_button_text(text)

def set_y_button_text(text):
    return _kipr.set_y_button_text(text)

def set_z_button_text(text):
    return _kipr.set_z_button_text(text)

def a_button():
    return _kipr.a_button()

def b_button():
    return _kipr.b_button()

def c_button():
    return _kipr.c_button()

def x_button():
    return _kipr.x_button()

def y_button():
    return _kipr.y_button()

def z_button():
    return _kipr.z_button()

def side_button():
    return _kipr.side_button()

def black_button():
    return _kipr.black_button()

def push_button():
    return _kipr.push_button()

def left_button():
    return _kipr.left_button()

def right_button():
    return _kipr.right_button()

def a_button_clicked():
    return _kipr.a_button_clicked()

def b_button_clicked():
    return _kipr.b_button_clicked()

def c_button_clicked():
    return _kipr.c_button_clicked()

def x_button_clicked():
    return _kipr.x_button_clicked()

def y_button_clicked():
    return _kipr.y_button_clicked()

def z_button_clicked():
    return _kipr.z_button_clicked()

def side_button_clicked():
    return _kipr.side_button_clicked()

def any_button():
    return _kipr.any_button()

def extra_buttons_show():
    return _kipr.extra_buttons_show()

def extra_buttons_hide():
    return _kipr.extra_buttons_hide()

def get_extra_buttons_visible():
    return _kipr.get_extra_buttons_visible()

def set_extra_buttons_visible(visible):
    return _kipr.set_extra_buttons_visible(visible)
class pixel(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    r = property(_kipr.pixel_r_get, _kipr.pixel_r_set)
    g = property(_kipr.pixel_g_get, _kipr.pixel_g_set)
    b = property(_kipr.pixel_b_get, _kipr.pixel_b_set)

    def __init__(self):
        _kipr.pixel_swiginit(self, _kipr.new_pixel())
    __swig_destroy__ = _kipr.delete_pixel

# Register pixel in _kipr:
_kipr.pixel_swigregister(pixel)

LOW_RES = _kipr.LOW_RES
MED_RES = _kipr.MED_RES
HIGH_RES = _kipr.HIGH_RES
TELLO_RES = _kipr.TELLO_RES
NATIVE_RES = _kipr.NATIVE_RES
WHITE_2016 = _kipr.WHITE_2016
BLACK_2017 = _kipr.BLACK_2017
TELLO = _kipr.TELLO

def camera_open():
    return _kipr.camera_open()

def camera_open_black():
    return _kipr.camera_open_black()

def camera_open_at_res(res):
    return _kipr.camera_open_at_res(res)

def camera_open_device(number, res):
    return _kipr.camera_open_device(number, res)

def camera_open_device_model_at_res(number, model, res):
    return _kipr.camera_open_device_model_at_res(number, model, res)

def camera_load_config(name):
    return _kipr.camera_load_config(name)

def get_camera_width():
    return _kipr.get_camera_width()

def get_camera_height():
    return _kipr.get_camera_height()

def camera_update():
    return _kipr.camera_update()

def get_camera_pixel(p):
    return _kipr.get_camera_pixel(p)

def get_channel_count():
    return _kipr.get_channel_count()

def get_object_count(channel):
    return _kipr.get_object_count(channel)

def get_object_data(channel, object):
    return _kipr.get_object_data(channel, object)

def get_code_num(channel, object):
    return _kipr.get_code_num(channel, object)

def get_object_data_length(channel, object):
    return _kipr.get_object_data_length(channel, object)

def get_object_confidence(channel, object):
    return _kipr.get_object_confidence(channel, object)

def get_object_area(channel, object):
    return _kipr.get_object_area(channel, object)

def get_object_bbox(channel, object):
    return _kipr.get_object_bbox(channel, object)

def get_object_bbox_ulx(channel, object):
    return _kipr.get_object_bbox_ulx(channel, object)

def get_object_bbox_uly(channel, object):
    return _kipr.get_object_bbox_uly(channel, object)

def get_object_bbox_brx(channel, object):
    return _kipr.get_object_bbox_brx(channel, object)

def get_object_bbox_bry(channel, object):
    return _kipr.get_object_bbox_bry(channel, object)

def get_object_bbox_width(channel, object):
    return _kipr.get_object_bbox_width(channel, object)

def get_object_bbox_height(channel, object):
    return _kipr.get_object_bbox_height(channel, object)

def get_object_centroid(channel, object):
    return _kipr.get_object_centroid(channel, object)

def get_object_centroid_column(channel, object):
    return _kipr.get_object_centroid_column(channel, object)

def get_object_centroid_x(channel, object):
    return _kipr.get_object_centroid_x(channel, object)

def get_object_centroid_row(channel, object):
    return _kipr.get_object_centroid_row(channel, object)

def get_object_centroid_y(channel, object):
    return _kipr.get_object_centroid_y(channel, object)

def get_object_center(channel, object):
    return _kipr.get_object_center(channel, object)

def get_object_center_column(channel, object):
    return _kipr.get_object_center_column(channel, object)

def get_object_center_x(channel, object):
    return _kipr.get_object_center_x(channel, object)

def get_object_center_row(channel, object):
    return _kipr.get_object_center_row(channel, object)

def get_object_center_y(channel, object):
    return _kipr.get_object_center_y(channel, object)

def camera_close():
    return _kipr.camera_close()

def set_camera_config_base_path(path):
    return _kipr.set_camera_config_base_path(path)

def get_camera_frame_row(row):
    return _kipr.get_camera_frame_row(row)

def get_camera_frame():
    return _kipr.get_camera_frame()

def get_camera_element_size():
    return _kipr.get_camera_element_size()

def calibrate_compass():
    return _kipr.calibrate_compass()

def set_compass_params(meanX, meanY, meanZ, W1, W2, div_E1, div_E2):
    return _kipr.set_compass_params(meanX, meanY, meanZ, W1, W2, div_E1, div_E2)

def get_compass_angle():
    return _kipr.get_compass_angle()

def console_clear():
    return _kipr.console_clear()

def kipr_git_branch():
    return _kipr.kipr_git_branch()

def kipr_git_commit_hash():
    return _kipr.kipr_git_commit_hash()

def kipr_version_major():
    return _kipr.kipr_version_major()

def kipr_version_minor():
    return _kipr.kipr_version_minor()

def kipr_version_patch():
    return _kipr.kipr_version_patch()

def kipr_version():
    return _kipr.kipr_version()

def kipr_build_datetime():
    return _kipr.kipr_build_datetime()

def create_connect():
    return _kipr.create_connect()

def create_connect_once():
    return _kipr.create_connect_once()

def create_disconnect():
    return _kipr.create_disconnect()

def create_passive():
    return _kipr.create_passive()

def create_safe():
    return _kipr.create_safe()

def create_full():
    return _kipr.create_full()

def get_create_mode():
    return _kipr.get_create_mode()

def get_create_lbump():
    return _kipr.get_create_lbump()

def get_create_rbump():
    return _kipr.get_create_rbump()

def get_create_lwdrop():
    return _kipr.get_create_lwdrop()

def get_create_cwdrop():
    return _kipr.get_create_cwdrop()

def get_create_rwdrop():
    return _kipr.get_create_rwdrop()

def get_create_wall():
    return _kipr.get_create_wall()

def get_create_lcliff():
    return _kipr.get_create_lcliff()

def get_create_lfcliff():
    return _kipr.get_create_lfcliff()

def get_create_rfcliff():
    return _kipr.get_create_rfcliff()

def get_create_rcliff():
    return _kipr.get_create_rcliff()

def get_create_llightbump():
    return _kipr.get_create_llightbump()

def get_create_lflightbump():
    return _kipr.get_create_lflightbump()

def get_create_lclightbump():
    return _kipr.get_create_lclightbump()

def get_create_rclightbump():
    return _kipr.get_create_rclightbump()

def get_create_rflightbump():
    return _kipr.get_create_rflightbump()

def get_create_rlightbump():
    return _kipr.get_create_rlightbump()

def get_create_llightbump_amt():
    return _kipr.get_create_llightbump_amt()

def get_create_rlightbump_amt():
    return _kipr.get_create_rlightbump_amt()

def get_create_lflightbump_amt():
    return _kipr.get_create_lflightbump_amt()

def get_create_lclightbump_amt():
    return _kipr.get_create_lclightbump_amt()

def get_create_rclightbump_amt():
    return _kipr.get_create_rclightbump_amt()

def get_create_rflightbump_amt():
    return _kipr.get_create_rflightbump_amt()

def get_create_vwall():
    return _kipr.get_create_vwall()

def get_create_infrared():
    return _kipr.get_create_infrared()

def get_create_advance_button():
    return _kipr.get_create_advance_button()

def get_create_play_button():
    return _kipr.get_create_play_button()

def get_create_normalized_angle():
    return _kipr.get_create_normalized_angle()

def set_create_normalized_angle(angle):
    return _kipr.set_create_normalized_angle(angle)

def get_create_total_angle():
    return _kipr.get_create_total_angle()

def set_create_total_angle(angle):
    return _kipr.set_create_total_angle(angle)

def get_create_distance():
    return _kipr.get_create_distance()

def set_create_distance(dist):
    return _kipr.set_create_distance(dist)

def get_create_battery_charging_state():
    return _kipr.get_create_battery_charging_state()

def get_create_battery_temp():
    return _kipr.get_create_battery_temp()

def get_create_battery_charge():
    return _kipr.get_create_battery_charge()

def get_create_battery_capacity():
    return _kipr.get_create_battery_capacity()

def get_create_wall_amt():
    return _kipr.get_create_wall_amt()

def get_create_lcliff_amt():
    return _kipr.get_create_lcliff_amt()

def get_create_lfcliff_amt():
    return _kipr.get_create_lfcliff_amt()

def get_create_rfcliff_amt():
    return _kipr.get_create_rfcliff_amt()

def get_create_rcliff_amt():
    return _kipr.get_create_rcliff_amt()

def get_create_song_number():
    return _kipr.get_create_song_number()

def get_create_song_playing():
    return _kipr.get_create_song_playing()

def create_stop():
    return _kipr.create_stop()

def create_drive(speed, radius):
    return _kipr.create_drive(speed, radius)

def create_drive_straight(speed):
    return _kipr.create_drive_straight(speed)

def create_spin_CW(speed):
    return _kipr.create_spin_CW(speed)

def create_spin_CCW(speed):
    return _kipr.create_spin_CCW(speed)

def create_drive_direct(l_speed, r_speed):
    return _kipr.create_drive_direct(l_speed, r_speed)

def create_spin_block(speed, angle):
    return _kipr.create_spin_block(speed, angle)

def _create_get_raw_encoders(lenc, renc):
    return _kipr._create_get_raw_encoders(lenc, renc)

def create_load_song(song, length, num):
    return _kipr.create_load_song(song, length, num)

def create_play_song(num):
    return _kipr.create_play_song(num)

def create_read_block(data, count):
    return _kipr.create_read_block(data, count)

def create_write_byte(byte):
    return _kipr.create_write_byte(byte)

def create_clear_serial_buffer():
    return _kipr.create_clear_serial_buffer()
Baud57600 = _kipr.Baud57600
Baud115200 = _kipr.Baud115200

def get_create_baud_rate():
    return _kipr.get_create_baud_rate()

def set_create_baud_rate(baudRate):
    return _kipr.set_create_baud_rate(baudRate)

def digital(port):
    return _kipr.digital(port)

def set_digital_value(port, value):
    return _kipr.set_digital_value(port, value)

def get_digital_value(port):
    return _kipr.get_digital_value(port)

def set_digital_output(port, out):
    return _kipr.set_digital_output(port, out)

def get_digital_output(port):
    return _kipr.get_digital_output(port)

def get_digital_pullup(port):
    return _kipr.get_digital_pullup(port)

def set_digital_pullup(port, pullup):
    return _kipr.set_digital_pullup(port, pullup)
class point2(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    x = property(_kipr.point2_x_get, _kipr.point2_x_set)
    y = property(_kipr.point2_y_get, _kipr.point2_y_set)

    def __init__(self):
        _kipr.point2_swiginit(self, _kipr.new_point2())
    __swig_destroy__ = _kipr.delete_point2

# Register point2 in _kipr:
_kipr.point2_swigregister(point2)

class point3(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    x = property(_kipr.point3_x_get, _kipr.point3_x_set)
    y = property(_kipr.point3_y_get, _kipr.point3_y_set)
    z = property(_kipr.point3_z_get, _kipr.point3_z_set)

    def __init__(self):
        _kipr.point3_swiginit(self, _kipr.new_point3())
    __swig_destroy__ = _kipr.delete_point3

# Register point3 in _kipr:
_kipr.point3_swigregister(point3)

class rectangle(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    ulx = property(_kipr.rectangle_ulx_get, _kipr.rectangle_ulx_set)
    uly = property(_kipr.rectangle_uly_get, _kipr.rectangle_uly_set)
    width = property(_kipr.rectangle_width_get, _kipr.rectangle_width_set)
    height = property(_kipr.rectangle_height_get, _kipr.rectangle_height_set)

    def __init__(self):
        _kipr.rectangle_swiginit(self, _kipr.new_rectangle())
    __swig_destroy__ = _kipr.delete_rectangle

# Register rectangle in _kipr:
_kipr.rectangle_swigregister(rectangle)


def create_point2(x, y):
    return _kipr.create_point2(x, y)

def create_point3(x, y, z):
    return _kipr.create_point3(x, y, z)

def create_rectangle(ulx, uly, width, height):
    return _kipr.create_rectangle(ulx, uly, width, height)

def graphics_open(width, height):
    return _kipr.graphics_open(width, height)

def graphics_close():
    return _kipr.graphics_close()

def graphics_update():
    return _kipr.graphics_update()

def graphics_clear():
    return _kipr.graphics_clear()
RGB = _kipr.RGB
BGR = _kipr.BGR

def graphics_blit(data, x, y, width, height):
    return _kipr.graphics_blit(data, x, y, width, height)

def graphics_blit_region(data, sx, sy, ex, ey, width, height, dx, dy):
    return _kipr.graphics_blit_region(data, sx, sy, ex, ey, width, height, dx, dy)

def graphics_blit_enc(data, enc, x, y, width, height):
    return _kipr.graphics_blit_enc(data, enc, x, y, width, height)

def graphics_blit_region_enc(data, enc, sx, sy, ex, ey, width, height, dx, dy):
    return _kipr.graphics_blit_region_enc(data, enc, sx, sy, ex, ey, width, height, dx, dy)

def graphics_fill(r, g, b):
    return _kipr.graphics_fill(r, g, b)

def graphics_pixel(x, y, r, g, b):
    return _kipr.graphics_pixel(x, y, r, g, b)

def graphics_line(x1, y1, x2, y2, r, g, b):
    return _kipr.graphics_line(x1, y1, x2, y2, r, g, b)

def graphics_circle(cx, cy, radius, r, g, b):
    return _kipr.graphics_circle(cx, cy, radius, r, g, b)

def graphics_circle_fill(cx, cy, radius, r, g, b):
    return _kipr.graphics_circle_fill(cx, cy, radius, r, g, b)

def graphics_rectangle(x1, y1, x2, y2, r, g, b):
    return _kipr.graphics_rectangle(x1, y1, x2, y2, r, g, b)

def graphics_rectangle_fill(x1, y1, x2, y2, r, g, b):
    return _kipr.graphics_rectangle_fill(x1, y1, x2, y2, r, g, b)

def graphics_triangle(x1, y1, x2, y2, x3, y3, r, g, b):
    return _kipr.graphics_triangle(x1, y1, x2, y2, x3, y3, r, g, b)

def graphics_triangle_fill(x1, y1, x2, y2, x3, y3, r, g, b):
    return _kipr.graphics_triangle_fill(x1, y1, x2, y2, x3, y3, r, g, b)

def get_key_state(key):
    return _kipr.get_key_state(key)

def get_mouse_position(x, y):
    return _kipr.get_mouse_position(x, y)

def get_mouse_middle_button():
    return _kipr.get_mouse_middle_button()

def get_mouse_left_button():
    return _kipr.get_mouse_left_button()

def get_mouse_right_button():
    return _kipr.get_mouse_right_button()

def gyro_x():
    return _kipr.gyro_x()

def gyro_y():
    return _kipr.gyro_y()

def gyro_z():
    return _kipr.gyro_z()

def gyro_calibrate():
    return _kipr.gyro_calibrate()

def magneto_x():
    return _kipr.magneto_x()

def magneto_y():
    return _kipr.magneto_y()

def magneto_z():
    return _kipr.magneto_z()

def get_motor_position_counter(motor):
    return _kipr.get_motor_position_counter(motor)

def gmpc(motor):
    return _kipr.gmpc(motor)

def clear_motor_position_counter(motor):
    return _kipr.clear_motor_position_counter(motor)

def cmpc(motor):
    return _kipr.cmpc(motor)

def move_at_velocity(motor, velocity):
    return _kipr.move_at_velocity(motor, velocity)

def mav(motor, velocity):
    return _kipr.mav(motor, velocity)

def move_to_position(motor, speed, goal_pos):
    return _kipr.move_to_position(motor, speed, goal_pos)

def mtp(motor, speed, goal_pos):
    return _kipr.mtp(motor, speed, goal_pos)

def move_relative_position(motor, speed, delta_pos):
    return _kipr.move_relative_position(motor, speed, delta_pos)

def mrp(motor, speed, delta_pos):
    return _kipr.mrp(motor, speed, delta_pos)

def set_pid_gains(motor, p, i, d, pd, id, dd):
    return _kipr.set_pid_gains(motor, p, i, d, pd, id, dd)

def get_pid_gains(motor, p, i, d, pd, id, dd):
    return _kipr.get_pid_gains(motor, p, i, d, pd, id, dd)

def freeze(motor):
    return _kipr.freeze(motor)

def get_motor_done(motor):
    return _kipr.get_motor_done(motor)

def block_motor_done(motor):
    return _kipr.block_motor_done(motor)

def bmd(motor):
    return _kipr.bmd(motor)

def setpwm(motor, pwm):
    return _kipr.setpwm(motor, pwm)

def getpwm(motor):
    return _kipr.getpwm(motor)

def fd(motor):
    return _kipr.fd(motor)

def bk(motor):
    return _kipr.bk(motor)

def motor(motor, percent):
    return _kipr.motor(motor, percent)

def baasbennaguui(motor, percent):
    return _kipr.baasbennaguui(motor, percent)

def motor_power(motor, percent):
    return _kipr.motor_power(motor, percent)

def off(motor):
    return _kipr.off(motor)

def alloff():
    return _kipr.alloff()

def ao():
    return _kipr.ao()

def enable_servo(port):
    return _kipr.enable_servo(port)

def disable_servo(port):
    return _kipr.disable_servo(port)

def enable_servos():
    return _kipr.enable_servos()

def disable_servos():
    return _kipr.disable_servos()

def set_servo_enabled(port, enabled):
    return _kipr.set_servo_enabled(port, enabled)

def get_servo_enabled(port):
    return _kipr.get_servo_enabled(port)

def get_servo_position(port):
    return _kipr.get_servo_position(port)

def set_servo_position(port, position):
    return _kipr.set_servo_position(port, position)
TELLO_SSID_LENGTH = _kipr.TELLO_SSID_LENGTH
TELLO_BUFSIZE = _kipr.TELLO_BUFSIZE
TELLO_CMD_PORT = _kipr.TELLO_CMD_PORT
TELLO_STATE_PORT = _kipr.TELLO_STATE_PORT
TELLO_VIDEO_PORT = _kipr.TELLO_VIDEO_PORT
TELLO_TIMEOUT = _kipr.TELLO_TIMEOUT
TELLO_SUBNET = _kipr.TELLO_SUBNET
NET_WAIT_COUNT = _kipr.NET_WAIT_COUNT
NET_WAIT_TIME = _kipr.NET_WAIT_TIME
TELLO_WAIT = _kipr.TELLO_WAIT
class tello_ssid(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    ssid = property(_kipr.tello_ssid_ssid_get, _kipr.tello_ssid_ssid_set)

    def __init__(self):
        _kipr.tello_ssid_swiginit(self, _kipr.new_tello_ssid())
    __swig_destroy__ = _kipr.delete_tello_ssid

# Register tello_ssid in _kipr:
_kipr.tello_ssid_swigregister(tello_ssid)

class tello_info(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    ssid = property(_kipr.tello_info_ssid_get, _kipr.tello_info_ssid_set)
    tello_cmd_addr = property(_kipr.tello_info_tello_cmd_addr_get, _kipr.tello_info_tello_cmd_addr_set)
    tello_cmd_socket = property(_kipr.tello_info_tello_cmd_socket_get, _kipr.tello_info_tello_cmd_socket_set)

    def __init__(self):
        _kipr.tello_info_swiginit(self, _kipr.new_tello_info())
    __swig_destroy__ = _kipr.delete_tello_info

# Register tello_info in _kipr:
_kipr.tello_info_swigregister(tello_info)


def tellos_find():
    return _kipr.tellos_find()

def tello_connect(arg1, tello_ssid):
    return _kipr.tello_connect(arg1, tello_ssid)

def tello_send(tello, command):
    return _kipr.tello_send(tello, command)

def tello_send_wait(arg1, command, seconds):
    return _kipr.tello_send_wait(arg1, command, seconds)

def tello_send_no_wait(arg1, command):
    return _kipr.tello_send_no_wait(arg1, command)

def tello_send_wait_noretry(tello, command, wait):
    return _kipr.tello_send_wait_noretry(tello, command, wait)
TELLO_RETURN_OK = _kipr.TELLO_RETURN_OK
TELLO_RETURN_GARBAGE = _kipr.TELLO_RETURN_GARBAGE
TELLO_RETURN_ERROR = _kipr.TELLO_RETURN_ERROR
TELLO_RETURN_TIMEOUT = _kipr.TELLO_RETURN_TIMEOUT
TELLO_RETURN_CMD_NOT_COMPLETE = _kipr.TELLO_RETURN_CMD_NOT_COMPLETE
TELLO_RETURN_INSUFFICIANT_LIGHT = _kipr.TELLO_RETURN_INSUFFICIANT_LIGHT
TELLO_RETURN_UNKNOWN = _kipr.TELLO_RETURN_UNKNOWN

def wpa_sup_connect():
    return _kipr.wpa_sup_connect()

def wpa_cmd(cmd, buf):
    return _kipr.wpa_cmd(cmd, buf)

def msleep(msecs):
    return _kipr.msleep(msecs)

def systime():
    return _kipr.systime()

def seconds():
    return _kipr.seconds()

def wait_for_milliseconds(msecs):
    return _kipr.wait_for_milliseconds(msecs)

def wait_for_touch(port):
    return _kipr.wait_for_touch(port)

def wait_for_a_button():
    return _kipr.wait_for_a_button()

def wait_for_b_button():
    return _kipr.wait_for_b_button()

def wait_for_c_button():
    return _kipr.wait_for_c_button()

def wait_for_x_button():
    return _kipr.wait_for_x_button()

def wait_for_y_button():
    return _kipr.wait_for_y_button()

def wait_for_z_button():
    return _kipr.wait_for_z_button()

def wait_for_side_button():
    return _kipr.wait_for_side_button()

def wait_for_any_button():
    return _kipr.wait_for_any_button()

def wait_for_a_button_clicked():
    return _kipr.wait_for_a_button_clicked()

def wait_for_b_button_clicked():
    return _kipr.wait_for_b_button_clicked()

def wait_for_c_button_clicked():
    return _kipr.wait_for_c_button_clicked()

def wait_for_x_button_clicked():
    return _kipr.wait_for_x_button_clicked()

def wait_for_y_button_clicked():
    return _kipr.wait_for_y_button_clicked()

def wait_for_z_button_clicked():
    return _kipr.wait_for_z_button_clicked()

def wait_for_side_button_clicked():
    return _kipr.wait_for_side_button_clicked()


